import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeInitScript = `
    (function() {
      // اگر قبلاً کاربر انتخاب کرده
      var stored = null;
      try {
        stored = localStorage.getItem('theme');
      } catch (e) {}

      var systemPrefersDark = window.matchMedia &&
        window.matchMedia('(prefers-color-scheme: dark)').matches;

      var theme = stored || (systemPrefersDark ? 'dark' : 'light');
      var root = document.documentElement;
      root.setAttribute('data-theme', theme);
    })();
  `;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground dark:bg-foreground dark:text-background`}
      >
        <StoreProvider>
          <div className="max-w-7xl m-auto">
            <Header />
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
